### ISSUE TITLE
Why is there "tests" executable in addition to a test suite?

### ISSUE THREAD

**Issue by ethercrow** [cies/htoml#18]
Because of that depending on htoml brings test-related libraries like hspec and tasty into clients' dependency trees.

Also plain `cabal/stack install htoml` populates your path with a confusing `tests` executable.

**Comment by cies** [comment]
I'm convinced it should go. The reason it is there is because I used some sort of project init (forgot which one, maybe the "holy-project" one). I also wondered what it was doing there, but it never hurt me so I kept it around.

I'll fix it and upload a new version to Hackage.

Thanks for reporting, and thanks for your work on Yi. Frickin' awesome stuff!

**Comment by ethercrow** [comment]
> I'll fix it and upload a new version to Hackage.

Thanks!

> thanks for your work on Yi. Frickin' awesome stuff!

My pleasure.
