### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by flip111** [cies/htoml#20]
How is one suppose to validate the toml file? Maybe, as recommendation, there is a library that goes well with htoml?

**Comment by cies** [comment]
Validation is implicit in parsing the TOML file. If it parses it is valid. At this point there is no TOML-schema (like there is JSON-schema or XML-schema/RelaxNG), but since TOML is very easy to transpose to JSON (`htoml` supports this) you could use JSON-schema to validate your TOML. Bonus, if you want to validate type information that is not explicit in JSON, then you could use the `ToBsJSON`, which encodes the types into the JSON output.

Hope this answers your question.

**Comment by flip111** [comment]
Great idea, thank you !

**Comment by cies** [comment]
Your welcome!
